[build]
  publish = "output"
  command = "pip install -e . && python ss_script.py"

[build.environment]
  PYTHON_VERSION = "3.8"
  PYTHONPATH = "."

# Build settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true